services:
  - type: web
    name: smart-hr-management-system
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-db4d4kt9fdbs73bj849g-a/project_4d6z
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: JWT_SECRET
        generateValue: true
